### ISSUE TITLE
Schema for src string is not working with the fileList.map of testcafe parse-file-list.js.

### ISSUE THREAD

**Issue by psander-com** [politie/angular-testcafe#34]
Hi,

i am not quite sure but it seems that the schema is not matching the requirements for the src file list parser.

https://github.com/DevExpress/testcafe/blob/master/src/utils/parse-file-list.js#L35

When i change the schema, from string to array - it seems to be working.
Please have a look.

Kind regards and thanks for this package.

**Comment by timnederhoff** [comment]
Yeah I was trying to find why it didn't accept a string anyway. But still no clue. So I made a fix in fde6e808ef6496b014437465227a8daba3f94da8
expect to release today.
thanks for your comment
