### ISSUE TITLE
.testcaferc.json location in angular.json

### ISSUE THREAD

**Issue by alemp** [politie/angular-testcafe#41]
Is it possible to create a property in schemas (f.e. configFilePath) to set up .testcaferc.json location instead of configure options separately.

It will be nice when you already have a .testcaferc.json and you don't want to describe everything again in angular.json file.

Another advantage is to have all configurations in one place.

Thanks in advance.

**Comment by timnederhoff** [comment]
Hi @alemp,
The idea using this builder is to configure your testcafe run(s) in the angular.json, I you want to use your testcaferc config, I suggest you call testcafe from the command line. This builder uses the programming interface which does not support the use of testcafe config file.

Best practice for you is probably to transfer your setting over to one or more angular.json configs.
