### ISSUE TITLE
Anything from todo list is up for grabs?

### ISSUE THREAD

**Issue by AdaskoTheBeAsT** [politie/angular-testcafe#54]
Hi,

Anything from todo list is up for grabs? I could prepare some changes if you accept pull reqs.

**Comment by timnederhoff** [comment]
Hi @AdaskoTheBeAsT, sorry to inform you that this repo is poorly maintained. A fork over here: https://github.com/testcafe-community/nx-builder is more recently updated, and elaborated with new features. It's published here: https://www.npmjs.com/package/@testcafe-community/nx-builder
